name: stat-arb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - bottleneck
  - numexpr
  - requests
  - httpx
  - pyyaml
  - beautifulsoup4
  - lxml
  - dash
  - flask
  - pandas-datareader
